version: "3"

services:
  server:
    build: master/
    volumes:
      - ./master:/master
    command: cargo run --manifest-path /master/Cargo.toml
    ports:
      - 7878:7878


  secondary_1:
    build: sec/
    volumes:
      - ./sec:/sec
    ports:
      - "5001:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - SLEEP_TIMEOUT=1


  secondary_2:
    build: sec/
    volumes:
      - ./sec:/sec
    ports:
      - "5002:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - SLEEP_TIMEOUT=1

  #   # The keyword'depends_on' allows you to define whether the service
  #   # should wait until other services are ready before launching.
  #   # Here, we want the 'sec' service to wait until the 'server' service is ready.
  #   depends_on:
  #     - server
