version: "3"

services:
  server:
    build: master/
    volumes:
      - ./master:/master
    command: cargo run --manifest-path /master/Cargo.toml
    ports:
      - 7878:7878


  secondary:
    build: sec/
    volumes:
      - ./sec:/sec
    ports:
      - "3000-3020:3333"

  #   # The keyword'depends_on' allows you to define whether the service
  #   # should wait until other services are ready before launching.
  #   # Here, we want the 'sec' service to wait until the 'server' service is ready.
  #   depends_on:
  #     - server
