version: "3"

services:
  server:
    build: master/
    volumes:
      - ./master:/master
    command: cargo run --manifest-path /master/Cargo.toml
    ports:
      - 7878:7878


  sec1:
    build: sec/
    volumes:
      - ./sec:/sec
    # command: python ./secondary.py --port 5001
    command: python ./sec/sec1.py 5001
    # ports:
    #   - 5001:5001


  sec2:
    build: sec/
    volumes:
      - ./sec:/sec
    # command: python ./secondary.py --port 5002
    command: python ./sec/sec5.py 5002

  #   # The keyword'depends_on' allows you to define whether the service
  #   # should wait until other services are ready before launching.
  #   # Here, we want the 'sec' service to wait until the 'server' service is ready.
  #   depends_on:
  #     - server
