version: "3"

services:
  server:
    build: master/
    volumes:
      - ./master:/master
    command: cargo run --manifest-path /master/Cargo.toml tcp
    ports:
      - 7878:7878


  sec1:
    build: sec/
    command: python ./secondary.py --port 5001

  sec2:
    build: sec/
    command: python ./secondary.py --port 5002

    # # The keyword 'network_mode' is used to define the network type.
    # # Here we define that the container can access to the 'localhost' of the computer.
    # network_mode: host

    # The keyword'depends_on' allows you to define whether the service
    # should wait until other services are ready before launching.
    # Here, we want the 'sec' service to wait until the 'server' service is ready.
    depends_on:
      - server
